---
users: ["jordan"]
sudoers_group : "wheel"
transmission_download_dir: "/var/lib/transmission/Downloads"
transmission_rpc_username: "jordan"
transmission_rpc_whitelist: "127.0.0.1,10.8.0.*,10.0.2.*"
