- name: Stop transmission daemon
  systemd:
    state: stopped
    name: transmission-daemon

- name: create configuration directory
  file:
    path: /etc/transmission-daemon
    state: directory

- name: copy settings.json
  template:
    src: etc/transmission-daemon/settings.json.j2
    dest: /etc/transmission-daemon/settings.json
