- name: ensure transmission service is stopped
  systemd:
    state: stopped
    name: transmission-daemon

- name: create configuration directory
  file:
    path: /etc/transmission-daemon
    state: directory

- name: create /var/lib/transmission/.config/transmission-daemon directory
  file:
    path: /var/lib/transmission/.config/transmission-daemon
    state: directory
    mode: 0755
    owner: transmission
    group: transmission

- name: copy settings.json
  template:
    src: var/lib/transmission/.config/transmission-daemon/settings.json.j2
    dest: /var/lib/transmission/.config/transmission-daemon/settings.json
