- include_tasks: install.yml
  become: true

- include_tasks: configure.yml
  become: true

- name: enable transmission daemon
  systemd:
    name: transmission-daemon
    enabled: yes
  become: true

- name: start transmission daemon
  systemd:
    name: transmission-daemon
    state: started
  become: true
