- hosts: all
  gather_facts: no
  pre_tasks:
    - name: update all packages
      yum:
        name: "*"
        state: latest
      become: true
      remote_user: root
  roles:
    - role: users
      tags:
        - users
    - role: gather_facts
      tags:
        - gather_facts
    - role: extra
      tags:
        - extra
    - role: transmission
      tags:
        - transmission
    - role: kyl191.openvpn
      tags:
        - vpn
    - role: iptables
      tags:
        - iptables
  tags:
    - vps
