- name: install epel-release
  yum:
    name: "epel-release"
    state: latest

- name: install extra packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - net-tools
    - htop
    - lsof
