- name: install iptables-services
  yum:
    name: "iptables-services"
    state: latest

- name: ensure iptables service is stopped
  systemd:
    state: stopped
    name: iptables

- name: copy iptables.sh
  template:
    src: root/iptables.sh.j2
    dest: /root/iptables.sh
    owner: root
    group: root
    mode: 0744

- name: execute iptables.sh
  shell: /root/iptables.sh > /root/iptables.log
