- name: create /etc/openvpn/easy-rsa/keys directory
  file:
    path: /etc/openvpn/easy-rsa/keys
    state: directory
    mode: 0755

# Ansible remote copy does not support recursive copy of directory
- name: copy key and certificate generation scripts
  shell: "cp -rf /usr/share/easy-rsa/2.0/* /etc/openvpn/easy-rsa"

- name: copy server.conf
  template:
    src: etc/openvpn/server.conf.j2
    dest: /etc/openvpn/server.conf

- name: copy vars
  template:
    src: etc/openvpn/easy-rsa/vars.j2
    dest: /etc/openvpn/easy-rsa/vars

- name: copy openssl.cnf
  template:
    src: etc/openvpn/easy-rsa/openssl.cnf.j2
    dest: /etc/openvpn/easy-rsa/openssl.cnf

- name: generate CA, server key and certificate, D-H key exchange file
  shell: "source ./vars && ./clean-all && ./build-ca --batch && ./build-key-server --batch server && ./build-dh"
  args:
    chdir: /etc/openvpn/easy-rsa

- name: copy CA, keys and certificate
  copy:
    src: /etc/openvpn/easy-rsa/keys/{{ item }}
    dest: /etc/openvpn/{{ item }}
    remote_src: yes
    directory_mode: yes
  with_items:
     - dh2048.pem
     - ca.crt
     - server.crt
     - server.key

- name: generate client keys
  shell: "source ./vars && ./build-key --batch {{ item }}"
  args:
    chdir: /etc/openvpn/easy-rsa
  with_items: "{{ vpn_clients }}"

- name: enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
