- name: install epel-release
  yum:
    name: "epel-release"
    state: latest

- name: update all packages
  yum:
    name: "*"
    state: latest

- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
     - openvpn
     - easy-rsa
