- include_tasks: install.yml

- include_tasks: configure.yml

- name: enable transmission service
  systemd:
    name: transmission-daemon
    enabled: yes

- name: start transmission service
  systemd:
    name: transmission-daemon
    state: started
