- hosts:
    vps
  pre_tasks:
    - name: update all packages
      yum:
        name: "*"
        state: latest
      become: true
  roles:
    - role: iptables
      tags:
        - iptables
    - role: extra
      tags:
        - extra
    - role: transmission
      tags:
        - transmission
    - role: vpn
      tags:
        - vpn
  tags:
    - vps