# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# prompt
export PS1="\e[0;32m\u@\h \W\\e[m> "

# aliases
alias l='ls -lh -G'
alias ls='ls -G'
alias l='ls -lh -G'
alias ll='ls -lh -G'
alias la='ls -lah -G'
alias grep='grep --color'
alias v='vim'
alias clean='rm *~; rm .*~; rm *.pyc'
